name: GitHub Actions Demo
on:
  schedule:
    - cron: "15 8 * * 0"
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Self checkout
        uses: actions/checkout@v3

      - name: Display event Name
        run: |
          echo "${{ github.event_name }}"
      - name: Display reference branch name
        run: |
          echo "${{ github.ref_name }}"
      - name: List all file in the environemnt
        run: ls
